#! /bin/bash
# This script is meant to evoke the algorithm without requiring any input arguments
#

# Define directory names and containers
FLYWHEEL_BASE=/flywheel/v0
INPUT_DIR=$FLYWHEEL_BASE/input/inspiration
OUTPUT_DIR=$FLYWHEEL_BASE/output
CONFIG_FILE=$FLYWHEEL_BASE/config.json
MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json
CONTAINER='[flywheel/lda-insp]'

# Check if the input directory is not empty
if [[ "$(ls -A $INPUT_DIR)" ]] ; then
    echo "$CONTAINER  Starting..."
else
    echo "Input directory is empty: $INPUT_DIR"
    exit 1
fi

# Find input file in input directory with the extension .zip, signifies zipped dir of DICOM files
input_file=`find $INPUT_DIR -iname '*.zip'`
bni=`basename "$input_file"`
filename="${bni%%.*}"

# Check if input file exists
if [[ -e $input_file ]] ; then
    echo "Unzipping DICOM files"
    unzip "$input_file" -d $INPUT_DIR
else
    echo "DICOM inputs were not found within input directory $INPUT_DIR"
    exit 1
fi

# Get inspiration threshold from config file if present
if [[ -e $CONFIG_FILE ]] ; then
    echo "Config file is present"
    ins_thresh=`cat $CONFIG_FILE | jq -r '.config.ins_thresh'`
else
    echo "Config file is not present, using default value"
    ins_thresh=`cat $MANIFEST_FILE | jq -r '.config.ins_thresh.default'`
fi

## Run the algorithm
/usr/local/bin/run_thresh_ct_lungs -i $INPUT_DIR -o $OUTPUT_DIR --ithresh $ins_thresh --research-label -d

# Remove some extra files and directories
for extrafile in 'ins_label_stats' 'lda_stats' 'report_ins_only.json' 'report_ins_only_pdf' 'stdout.log'
do
    extrafile_full=$OUTPUT_DIR/$extrafile
    if [[ -e $extrafile_full ]]; then
        rm -rf $extrafile_full
    fi
done

# Zip up DICOM file
dicom_dir="$OUTPUT_DIR/lda_ins_only"
if [[ -e $dicom_dir ]] ; then
    zip -r $OUTPUT_DIR/"$filename"'_lda_insp.dcm.zip' $dicom_dir
    rm -rf $dicom_dir
fi

# Rename pdf file
report_ins_only_pdf_file="$OUTPUT_DIR/report_ins_only.pdf"
if [[ -e $report_ins_only_pdf_file ]] ; then
    mv $report_ins_only_pdf_file $OUTPUT_DIR/"$filename"'_lda_insp.pdf'
fi
# Rename histogram.csv
histogram_csv_file="$OUTPUT_DIR/histograms.csv"
if [[ -e $histogram_csv_file ]] ; then
    mv $histogram_csv_file $OUTPUT_DIR/"$filename"'_lda_insp_hist.csv'
fi
# Rename histogram.csv
report_csv_file="$OUTPUT_DIR/report_ins_only.csv"
if [[ -e $report_csv_file ]] ; then
    mv $report_csv_file $OUTPUT_DIR/"$filename"'_lda_insp_report.csv'
fi

## Get a list of the files in the output directory
outputs=`find $OUTPUT_DIR -type f -name "*"`
# If outputs exist, then go on...
if [[ -z $outputs ]] ; then
    echo "No results found in output directory... Exiting"
    exit 1
else
    chmod -R 777 $OUTPUT_DIR
    echo -e "Wrote: `ls $OUTPUT_DIR`"
fi
exit 0
